### ISSUE TITLE
 Issue with Incomplete Calendar Output in irholiday

### ISSUE THREAD

**Issue by Hparvaresh** [hadi-gharibi/irholiday#4]
Hi irholiday Team,

I noticed that the calendar output is missing some dates, causing inaccuracies. For example:

```
1402-12-18  2024-03-08       0
1402-12-22  2024-03-12       0
1402-12-24  2024-03-14       0
1402-12-25  2024-03-15       0
1402-12-25  2024-03-15       0
1402-12-29  2024-03-19       1
```
Dates like December 18th, 22nd, 24th, and 25th are missing. Can you address this issue?

Thanks,

**Comment by hadi-gharibi** [comment]
@Hparvaresh Hey Hamed,

Thanks for bringing up the issue. Although I don't maintain this package anymore, I took a look at it, and it appears that during those days, there is no event. So, the absence of those days in the DF is a feature, not a bug. :D

it you are using this package for some sort of ML project, I would suggest to make your date range with pandas and left join it with the outcome of `irholiday`.
